// AUTO-GENERATED by build_store_catalog.js (G:\...\Carrum Downs\Store Catalog) — do not hand-edit.
var STORE_CATALOG = {
 "generated": "2026-06-10",
 "source": "106 invoice photos",
 "eposSource": "shopProducts.js",
 "products": [
  {
   "n": "(2)",
   "sups": [
    "Costa Farms"
   ],
   "stalls": [
    "7-11"
   ],
   "first": "2026-06-04",
   "last": "2026-06-04",
   "buys": 1,
   "epos": "CAPSICUM C/GRILL FRESH 2KG(2) , SFCGC2 SANDHURST"
  },
  {
   "n": "Adora Potatoes",
   "sups": [
    "GTV Produce"
   ],
   "stalls": [
    "104"
   ],
   "first": "2026-05-21",
   "last": "2026-05-21",
   "buys": 1,
   "epos": "Potato Brushed 5kg Bag"
  },
  {
   "n": "Apples",
   "sups": [
    "Independent Produce",
    "Market City Fruits"
   ],
   "stalls": [
    "19",
    "85"
   ],
   "first": "2026-05-21",
   "last": "2026-06-04",
   "buys": 3,
   "epos": "Apples Golden /kg"
  },
  {
   "n": "Apples Pink Lady Gala Jazz",
   "sups": [
    "Independent Produce"
   ],
   "stalls": [
    "85"
   ],
   "first": "2026-05-29",
   "last": "2026-05-29",
   "buys": 1,
   "epos": "Apples Golden /kg"
  },
  {
   "n": "Avocado",
   "sups": [
    "Arcella Bananas",
    "Costa Farms",
    "Sculli and Co"
   ],
   "stalls": [
    "57",
    "7-11"
   ],
   "first": "2026-05-21",
   "last": "2026-06-04",
   "buys": 4,
   "epos": "Avocado Hass Each"
  },
  {
   "n": "Baby Cos",
   "sups": [
    "Tripod Farmers Group"
   ],
   "stalls": [
    "109"
   ],
   "first": "2026-06-04",
   "last": "2026-06-04",
   "buys": 1,
   "epos": "Lettuce Baby Cos Twin Pack"
  },
  {
   "n": "Baby Indian Bittermelon",
   "sups": [
    "CN Fresh"
   ],
   "stalls": [
    "8"
   ],
   "first": "2026-06-01",
   "last": "2026-06-04",
   "buys": 2,
   "epos": "Bittermelon- Karela /kg"
  },
  {
   "n": "Banana",
   "sups": [
    "Arcella Bananas"
   ],
   "stalls": [
    "57"
   ],
   "first": "2026-05-29",
   "last": "2026-05-29",
   "buys": 1,
   "epos": "Bananas Extra Large /kg"
  },
  {
   "n": "Bananas",
   "sups": [
    "Arcella Bananas"
   ],
   "stalls": [
    "57"
   ],
   "first": "2026-06-01",
   "last": "2026-06-01",
   "buys": 1,
   "epos": "Bananas Extra Large /kg"
  },
  {
   "n": "Bananas Cavendish",
   "sups": [
    "Costa Farms"
   ],
   "stalls": [
    "7-11"
   ],
   "first": "2026-05-21",
   "last": "2026-05-21",
   "buys": 1,
   "epos": "Bananas Extra Large /kg"
  },
  {
   "n": "Beans",
   "sups": [
    "Independent Produce"
   ],
   "stalls": [
    "85"
   ],
   "first": "2026-05-22",
   "last": "2026-05-22",
   "buys": 1,
   "epos": "Beans Rugby /kg"
  },
  {
   "n": "Beetroot",
   "sups": [
    "Cong Thanh Vegetables",
    "Fresh Mix Produce",
    "Zee Fresh"
   ],
   "stalls": [
    "650",
    "831-833"
   ],
   "first": "2026-05-22",
   "last": "2026-06-01",
   "buys": 3,
   "epos": "Beetroot /kg"
  },
  {
   "n": "Bittermelon",
   "sups": [
    "CN Fresh"
   ],
   "stalls": [
    "8"
   ],
   "first": "2026-05-25",
   "last": "2026-05-25",
   "buys": 1,
   "epos": "Bittermelon- Karela /kg"
  },
  {
   "n": "Blackberries",
   "sups": [
    "Costa Farms",
    "Perfection Fresh"
   ],
   "stalls": [
    "47",
    "7-11"
   ],
   "first": "2026-05-25",
   "last": "2026-06-04",
   "buys": 3,
   "epos": "Blackberries Punnet"
  },
  {
   "n": "Blueberries",
   "sups": [
    "Costa Farms",
    "Perfection Fresh"
   ],
   "stalls": [
    "47",
    "7-11"
   ],
   "first": "2026-05-25",
   "last": "2026-06-04",
   "buys": 3,
   "epos": "Blueberries Punnet"
  },
  {
   "n": "Bok Choy",
   "sups": [
    "Fresh Mix Produce"
   ],
   "stalls": [
    "650"
   ],
   "first": "2026-05-29",
   "last": "2026-05-29",
   "buys": 1,
   "epos": "Bok Choy / Shanghai"
  },
  {
   "n": "Broccoli",
   "sups": [
    "Total Fresh Produce"
   ],
   "stalls": [
    "5"
   ],
   "first": "2026-05-21",
   "last": "2026-06-04",
   "buys": 2,
   "epos": null
  },
  {
   "n": "Cabbage",
   "sups": [
    "MazCorp"
   ],
   "stalls": [
    "129"
   ],
   "first": "2026-05-25",
   "last": "2026-05-25",
   "buys": 1,
   "epos": "Cabbage"
  },
  {
   "n": "Capsicum",
   "sups": [
    "Fresh Crop"
   ],
   "stalls": [],
   "first": "2026-05-21",
   "last": "2026-05-21",
   "buys": 1,
   "epos": "Capsicum Red /kg"
  },
  {
   "n": "Carrots",
   "sups": [
    "Fresh Berry",
    "Fresh Growers",
    "Gazzola Farms"
   ],
   "stalls": [
    "117",
    "119",
    "56"
   ],
   "first": "2026-05-25",
   "last": "2026-06-01",
   "buys": 4,
   "epos": "Carrot Cake MK"
  },
  {
   "n": "Cauliflower",
   "sups": [
    "Fresh Berry",
    "MazCorp",
    "Prestige Produce",
    "Young Sang & Co"
   ],
   "stalls": [
    "117",
    "129",
    "43",
    "45"
   ],
   "first": "2026-05-21",
   "last": "2026-06-04",
   "buys": 7,
   "epos": "Cauliflower Fresh /kg"
  },
  {
   "n": "Celery",
   "sups": [
    "Gazzola Farms"
   ],
   "stalls": [
    "56"
   ],
   "first": "2026-05-25",
   "last": "2026-06-04",
   "buys": 3,
   "epos": "Celery Size 10 each"
  },
  {
   "n": "Chillies",
   "sups": [
    "G Ferlazzo & Co",
    "Produce Of Virginia"
   ],
   "stalls": [
    "38",
    "99"
   ],
   "first": "2026-05-22",
   "last": "2026-05-25",
   "buys": 2,
   "epos": "Gourmet Chillies Crushed 20gm"
  },
  {
   "n": "Coconut",
   "sups": [
    "Hong Tin Fresh"
   ],
   "stalls": [
    "69"
   ],
   "first": "2026-05-29",
   "last": "2026-05-29",
   "buys": 1,
   "epos": "Coconut sip"
  },
  {
   "n": "Coconuts",
   "sups": [
    "Hong Tin Fresh"
   ],
   "stalls": [
    "69"
   ],
   "first": "2026-06-01",
   "last": "2026-06-01",
   "buys": 1,
   "epos": "Coconut sip"
  },
  {
   "n": "Coriander",
   "sups": [
    "Fresh Mix Produce",
    "Jims Fresh",
    "Mefaili Farms"
   ],
   "stalls": [
    "650",
    "738"
   ],
   "first": "2026-05-21",
   "last": "2026-06-01",
   "buys": 3,
   "epos": "Coriander Bunches"
  },
  {
   "n": "Corn",
   "sups": [
    "MazCorp"
   ],
   "stalls": [
    "129"
   ],
   "first": "2026-05-25",
   "last": "2026-05-25",
   "buys": 1,
   "epos": "Cheese Corn Toastie"
  },
  {
   "n": "Cucumber",
   "sups": [
    "Fresh Crop",
    "Latorre's"
   ],
   "stalls": [
    "63"
   ],
   "first": "2026-05-21",
   "last": "2026-06-01",
   "buys": 2,
   "epos": "Cucumbers bag small"
  },
  {
   "n": "Dragon",
   "sups": [
    "Sculli and Co"
   ],
   "stalls": [],
   "first": "2026-05-25",
   "last": "2026-05-25",
   "buys": 1,
   "epos": "Dragon Fruit Red Each"
  },
  {
   "n": "Dragonfruit",
   "sups": [
    "CK Tropical Produce",
    "Hong Tin Fresh"
   ],
   "stalls": [
    "42",
    "69"
   ],
   "first": "2026-06-01",
   "last": "2026-06-04",
   "buys": 2,
   "epos": "Dragon Fruit Red Each"
  },
  {
   "n": "Eggplant",
   "sups": [
    "Fresh Crop",
    "Latorre's"
   ],
   "stalls": [
    "63"
   ],
   "first": "2026-05-21",
   "last": "2026-06-04",
   "buys": 2,
   "epos": "Eggplant /kg"
  },
  {
   "n": "Endive",
   "sups": [
    "Fresh Mix Produce"
   ],
   "stalls": [
    "650"
   ],
   "first": "2026-05-29",
   "last": "2026-05-29",
   "buys": 1,
   "epos": "Endive"
  },
  {
   "n": "Fenugreek",
   "sups": [
    "Fresh Mix Produce",
    "Jims Fresh"
   ],
   "stalls": [
    "650",
    "738"
   ],
   "first": "2026-05-22",
   "last": "2026-06-01",
   "buys": 2,
   "epos": "Fenugreek Methi Bunch"
  },
  {
   "n": "Fruit",
   "sups": [
    "Sculli and Co"
   ],
   "stalls": [],
   "first": "2026-05-25",
   "last": "2026-05-25",
   "buys": 1,
   "epos": "Dragon Fruit Red Each"
  },
  {
   "n": "Garlic",
   "sups": [
    "Hong Tin Fresh",
    "MazCorp"
   ],
   "stalls": [
    "129",
    "69"
   ],
   "first": "2026-05-22",
   "last": "2026-06-04",
   "buys": 2,
   "epos": "Garlic Peeled"
  },
  {
   "n": "Ginger",
   "sups": [
    "G Ferlazzo & Co"
   ],
   "stalls": [
    "99"
   ],
   "first": "2026-05-22",
   "last": "2026-06-04",
   "buys": 2,
   "epos": "Ginger /kg"
  },
  {
   "n": "Gold Kiwifruit",
   "sups": [
    "Latorre's"
   ],
   "stalls": [
    "63"
   ],
   "first": "2026-05-29",
   "last": "2026-05-29",
   "buys": 1,
   "epos": "kiwi fruit GOLD /kg"
  },
  {
   "n": "Gourmet",
   "sups": [
    "Young Sang & Co"
   ],
   "stalls": [
    "45"
   ],
   "first": "2026-06-04",
   "last": "2026-06-04",
   "buys": 1,
   "epos": "Gourmet Salad Mix"
  },
  {
   "n": "Green Beans",
   "sups": [
    "Hong Tin Fresh"
   ],
   "stalls": [
    "69"
   ],
   "first": "2026-05-29",
   "last": "2026-05-29",
   "buys": 1,
   "epos": "Beans Rugby /kg"
  },
  {
   "n": "Green Chilli",
   "sups": [
    "Cong Thanh Vegetables"
   ],
   "stalls": [],
   "first": "2026-05-25",
   "last": "2026-05-25",
   "buys": 1,
   "epos": "Chilli Green"
  },
  {
   "n": "Greens",
   "sups": [
    "Fresh Mix Produce"
   ],
   "stalls": [
    "650"
   ],
   "first": "2026-05-29",
   "last": "2026-05-29",
   "buys": 1,
   "epos": "Chilli Green"
  },
  {
   "n": "Grey",
   "sups": [
    "Antonello Produce"
   ],
   "stalls": [
    "13"
   ],
   "first": "2026-06-01",
   "last": "2026-06-01",
   "buys": 1,
   "epos": "Tea- Earl Grey"
  },
  {
   "n": "Guava",
   "sups": [
    "CN Fresh",
    "Hong Tin Fresh"
   ],
   "stalls": [
    "69",
    "8"
   ],
   "first": "2026-05-25",
   "last": "2026-06-01",
   "buys": 2,
   "epos": "Guava /kg"
  },
  {
   "n": "Herbs",
   "sups": [
    "Ali Farm Fresh Produce",
    "Jims Fresh"
   ],
   "stalls": [
    "617-620",
    "738"
   ],
   "first": "2026-05-29",
   "last": "2026-06-04",
   "buys": 2,
   "epos": "Gourmet Mixed Herbs 10gm"
  },
  {
   "n": "Iceberg Lettuce",
   "sups": [
    "Melba Fresh"
   ],
   "stalls": [
    "66-68"
   ],
   "first": "2026-05-29",
   "last": "2026-05-29",
   "buys": 1,
   "epos": "Iceberg Lettuce each"
  },
  {
   "n": "Imperial",
   "sups": [
    "F & L Piccolo"
   ],
   "stalls": [
    "6-35"
   ],
   "first": "2026-05-25",
   "last": "2026-05-25",
   "buys": 1,
   "epos": "Mandarins Imperial /kg"
  },
  {
   "n": "Kale",
   "sups": [
    "Jims Fresh"
   ],
   "stalls": [
    "738"
   ],
   "first": "2026-05-22",
   "last": "2026-05-22",
   "buys": 1,
   "epos": "Kale Bunch"
  },
  {
   "n": "Kiwifruit",
   "sups": [
    "Premier Fresh Australia",
    "Sculli and Co"
   ],
   "stalls": [
    "87-97"
   ],
   "first": "2026-05-22",
   "last": "2026-06-04",
   "buys": 2,
   "epos": "kiwi fruit GOLD /kg"
  },
  {
   "n": "Kiwifruit Gold",
   "sups": [
    "Flavorite Marketing"
   ],
   "stalls": [
    "85"
   ],
   "first": "2026-06-01",
   "last": "2026-06-01",
   "buys": 1,
   "epos": "kiwi fruit GOLD /kg"
  },
  {
   "n": "Lemons",
   "sups": [
    "Louis"
   ],
   "stalls": [
    "35"
   ],
   "first": "2026-05-21",
   "last": "2026-05-21",
   "buys": 1,
   "epos": "Lemons each"
  },
  {
   "n": "Lettuce",
   "sups": [
    "MazCorp"
   ],
   "stalls": [
    "129"
   ],
   "first": "2026-05-22",
   "last": "2026-05-22",
   "buys": 1,
   "epos": "Iceberg Lettuce each"
  },
  {
   "n": "Mandarins",
   "sups": [
    "Barkers Fresh Produce",
    "F & L Piccolo",
    "Louis"
   ],
   "stalls": [
    "35",
    "51",
    "6-35"
   ],
   "first": "2026-05-21",
   "last": "2026-06-04",
   "buys": 5,
   "epos": "Mandarins Imperial /kg"
  },
  {
   "n": "Mango",
   "sups": [
    "Trescano"
   ],
   "stalls": [
    "79"
   ],
   "first": "2026-06-01",
   "last": "2026-06-01",
   "buys": 1,
   "epos": "COYO Coconut Milk Frozen Yoghurt Mango 500ml"
  },
  {
   "n": "Mangoes",
   "sups": [
    "Loc Bros Produce"
   ],
   "stalls": [
    "143"
   ],
   "first": "2026-05-22",
   "last": "2026-05-22",
   "buys": 1,
   "epos": "COYO Coconut Milk Frozen Yoghurt Mango 500ml"
  },
  {
   "n": "Melon",
   "sups": [
    "Hong Tin Fresh"
   ],
   "stalls": [
    "69"
   ],
   "first": "2026-05-29",
   "last": "2026-05-29",
   "buys": 1,
   "epos": "Melon Rock /kg"
  },
  {
   "n": "Mesclun",
   "sups": [
    "Melba Fresh"
   ],
   "stalls": [
    "66-68"
   ],
   "first": "2026-05-29",
   "last": "2026-05-29",
   "buys": 1,
   "epos": null
  },
  {
   "n": "Mint",
   "sups": [
    "Ali Farm Fresh Produce"
   ],
   "stalls": [
    "617-620"
   ],
   "first": "2026-06-04",
   "last": "2026-06-04",
   "buys": 1,
   "epos": "Mint Bunch"
  },
  {
   "n": "Mix",
   "sups": [
    "Tripod Farmers Group"
   ],
   "stalls": [
    "109"
   ],
   "first": "2026-05-22",
   "last": "2026-05-29",
   "buys": 2,
   "epos": "Gourmet Salad Mix"
  },
  {
   "n": "Mushrooms",
   "sups": [
    "Costa Farms"
   ],
   "stalls": [
    "7-11"
   ],
   "first": "2026-06-04",
   "last": "2026-06-04",
   "buys": 2,
   "epos": "Mushroom Brown /kg"
  },
  {
   "n": "Okra",
   "sups": [
    "Hong Tin Fresh",
    "Kim Phu Fresh"
   ],
   "stalls": [
    "69",
    "98"
   ],
   "first": "2026-05-22",
   "last": "2026-06-01",
   "buys": 4,
   "epos": "Okra Bhindi /kg"
  },
  {
   "n": "Onion",
   "sups": [
    "Jims Fresh"
   ],
   "stalls": [
    "738"
   ],
   "first": "2026-05-22",
   "last": "2026-05-22",
   "buys": 1,
   "epos": "Onion Spring Bunch"
  },
  {
   "n": "Onions",
   "sups": [
    "Antonello Produce",
    "Prestige Produce",
    "Ray Gregory & Sons"
   ],
   "stalls": [
    "13",
    "422-426",
    "43"
   ],
   "first": "2026-05-21",
   "last": "2026-06-04",
   "buys": 6,
   "epos": "Onion Spring Bunch"
  },
  {
   "n": "Oranges",
   "sups": [
    "Louis",
    "Ray Gregory & Sons"
   ],
   "stalls": [
    "35",
    "422-426"
   ],
   "first": "2026-05-21",
   "last": "2026-06-01",
   "buys": 4,
   "epos": "Oranges Naval /kg"
  },
  {
   "n": "Pak Choy",
   "sups": [
    "Jims Fresh"
   ],
   "stalls": [
    "738"
   ],
   "first": "2026-05-29",
   "last": "2026-05-29",
   "buys": 1,
   "epos": null
  },
  {
   "n": "Papaya",
   "sups": [
    "Sculli and Co"
   ],
   "stalls": [],
   "first": "2026-06-01",
   "last": "2026-06-04",
   "buys": 2,
   "epos": "Papaya Half"
  },
  {
   "n": "Passionfruit",
   "sups": [
    "Dykes Bros",
    "Ten Farms"
   ],
   "stalls": [
    "113",
    "133"
   ],
   "first": "2026-05-22",
   "last": "2026-06-04",
   "buys": 2,
   "epos": "Passionfruit Cheesecake Slice"
  },
  {
   "n": "Pears",
   "sups": [
    "Independent Produce"
   ],
   "stalls": [
    "85"
   ],
   "first": "2026-05-21",
   "last": "2026-06-01",
   "buys": 2,
   "epos": "Pears Corella /kg"
  },
  {
   "n": "Peeled",
   "sups": [
    "Hong Tin Fresh",
    "Hygiene Packers Wholesaler"
   ],
   "stalls": [
    "12",
    "69"
   ],
   "first": "2026-05-25",
   "last": "2026-06-04",
   "buys": 2,
   "epos": "Garlic Peeled"
  },
  {
   "n": "Persimmon",
   "sups": [
    "D & J Fruits"
   ],
   "stalls": [
    "112"
   ],
   "first": "2026-06-04",
   "last": "2026-06-04",
   "buys": 1,
   "epos": "Persimmon each"
  },
  {
   "n": "Persimmons",
   "sups": [
    "GTV Produce"
   ],
   "stalls": [
    "104"
   ],
   "first": "2026-05-22",
   "last": "2026-05-22",
   "buys": 1,
   "epos": "Persimmon each"
  },
  {
   "n": "Pineapple",
   "sups": [
    "L.A. Produce",
    "Sculli and Co"
   ],
   "stalls": [
    "46-48"
   ],
   "first": "2026-05-22",
   "last": "2026-06-01",
   "buys": 3,
   "epos": "Pineapple each"
  },
  {
   "n": "Potato",
   "sups": [
    "Hygiene Packers Wholesaler"
   ],
   "stalls": [
    "12"
   ],
   "first": "2026-05-25",
   "last": "2026-05-25",
   "buys": 1,
   "epos": "Potato Brushed 5kg Bag"
  },
  {
   "n": "Potatoes",
   "sups": [
    "Antonello Produce",
    "Prestige Produce",
    "Ray Gregory & Sons"
   ],
   "stalls": [
    "13",
    "422-426",
    "43"
   ],
   "first": "2026-05-21",
   "last": "2026-06-04",
   "buys": 6,
   "epos": "Potato Brushed 5kg Bag"
  },
  {
   "n": "Pumpkin",
   "sups": [
    "Antonello Produce",
    "Ray Gregory & Sons"
   ],
   "stalls": [
    "13",
    "422-426"
   ],
   "first": "2026-05-21",
   "last": "2026-06-04",
   "buys": 4,
   "epos": "Pumpkin Butternut /kg"
  },
  {
   "n": "Radish",
   "sups": [
    "Jims Fresh",
    "Kim Phu Fresh"
   ],
   "stalls": [
    "738",
    "98"
   ],
   "first": "2026-05-22",
   "last": "2026-05-29",
   "buys": 3,
   "epos": "Radish Red Bunch"
  },
  {
   "n": "Raspberries",
   "sups": [
    "Dykes Bros",
    "Fresh Berry"
   ],
   "stalls": [
    "117",
    "133"
   ],
   "first": "2026-05-22",
   "last": "2026-05-22",
   "buys": 2,
   "epos": "raspberry Punnnet"
  },
  {
   "n": "Red Brown Onions",
   "sups": [
    "Antonello Produce"
   ],
   "stalls": [
    "13"
   ],
   "first": "2026-05-29",
   "last": "2026-05-29",
   "buys": 1,
   "epos": "Onion Spring Bunch"
  },
  {
   "n": "Red Onions",
   "sups": [
    "Antonello Produce"
   ],
   "stalls": [
    "13"
   ],
   "first": "2026-05-25",
   "last": "2026-05-25",
   "buys": 1,
   "epos": "Onion Red 10kg Bag"
  },
  {
   "n": "Red Papaya",
   "sups": [
    "Costa Farms"
   ],
   "stalls": [
    "7-11"
   ],
   "first": "2026-05-21",
   "last": "2026-05-25",
   "buys": 2,
   "epos": "Papaya Red /kg"
  },
  {
   "n": "Rocket",
   "sups": [
    "Tripod Farmers Group"
   ],
   "stalls": [
    "109"
   ],
   "first": "2026-05-29",
   "last": "2026-06-04",
   "buys": 2,
   "epos": "Rocket Leaves box"
  },
  {
   "n": "Rocket Cos",
   "sups": [
    "Tripod Farmers Group"
   ],
   "stalls": [
    "109"
   ],
   "first": "2026-05-22",
   "last": "2026-05-22",
   "buys": 1,
   "epos": null
  },
  {
   "n": "Rockmelon",
   "sups": [
    "Fresh Crop",
    "Latorre's",
    "Premier Fresh Australia"
   ],
   "stalls": [
    "63",
    "87-97"
   ],
   "first": "2026-05-22",
   "last": "2026-06-01",
   "buys": 3,
   "epos": "Melon Rock /kg"
  },
  {
   "n": "Salad",
   "sups": [
    "Tripod Farmers Group"
   ],
   "stalls": [
    "109"
   ],
   "first": "2026-05-22",
   "last": "2026-05-29",
   "buys": 2,
   "epos": "Gourmet Salad Mix"
  },
  {
   "n": "Shallots",
   "sups": [
    "Gazzola Farms"
   ],
   "stalls": [
    "56"
   ],
   "first": "2026-05-25",
   "last": "2026-05-25",
   "buys": 1,
   "epos": null
  },
  {
   "n": "Spinach",
   "sups": [
    "Jims Fresh",
    "Tripod Farmers Group",
    "Zee Fresh"
   ],
   "stalls": [
    "109",
    "738",
    "831-833"
   ],
   "first": "2026-05-22",
   "last": "2026-05-29",
   "buys": 4,
   "epos": "Spinach Bunch"
  },
  {
   "n": "Spring Onion",
   "sups": [
    "Ali Farm Fresh Produce"
   ],
   "stalls": [
    "617-620"
   ],
   "first": "2026-06-04",
   "last": "2026-06-04",
   "buys": 1,
   "epos": "Onion Spring Bunch"
  },
  {
   "n": "Strawberries",
   "sups": [
    "Costa Farms"
   ],
   "stalls": [
    "7-11"
   ],
   "first": "2026-05-25",
   "last": "2026-05-25",
   "buys": 1,
   "epos": "Strawberries 250g"
  },
  {
   "n": "Sumich",
   "sups": [
    "Fresh Growers"
   ],
   "stalls": [
    "119"
   ],
   "first": "2026-05-29",
   "last": "2026-06-01",
   "buys": 2,
   "epos": null
  },
  {
   "n": "Sweet Potato",
   "sups": [
    "Ray Gregory & Sons"
   ],
   "stalls": [
    "422-426"
   ],
   "first": "2026-05-22",
   "last": "2026-05-22",
   "buys": 1,
   "epos": "Potato Sweet Potato Medium /kg"
  },
  {
   "n": "Tomato",
   "sups": [
    "Fresh Crop"
   ],
   "stalls": [],
   "first": "2026-05-21",
   "last": "2026-05-21",
   "buys": 1,
   "epos": "Tomato Cherry Punnets"
  },
  {
   "n": "Tomatoes",
   "sups": [
    "Costa Farms",
    "G Ferlazzo & Co",
    "Glow Fresh",
    "Young Sang & Co"
   ],
   "stalls": [
    "45",
    "7-11",
    "99"
   ],
   "first": "2026-05-21",
   "last": "2026-06-04",
   "buys": 4,
   "epos": "Tomato Cherry Punnets"
  },
  {
   "n": "Turmeric",
   "sups": [
    "Fresh Mix Produce",
    "Produce Of Virginia"
   ],
   "stalls": [
    "38",
    "650"
   ],
   "first": "2026-05-25",
   "last": "2026-06-01",
   "buys": 2,
   "epos": "Turmeric Fresh /kg"
  },
  {
   "n": "Watermelon",
   "sups": [
    "Emilio's Finest",
    "Ray Gregory & Sons"
   ],
   "stalls": [
    "422-426",
    "53-55"
   ],
   "first": "2026-05-21",
   "last": "2026-05-29",
   "buys": 2,
   "epos": "Watermelon Seedless /kg"
  },
  {
   "n": "White Cup Mushrooms",
   "sups": [
    "Costa Farms"
   ],
   "stalls": [
    "7-11"
   ],
   "first": "2026-05-22",
   "last": "2026-05-25",
   "buys": 2,
   "epos": "Mushrooms White Cup /kg"
  },
  {
   "n": "Wild",
   "sups": [
    "Tripod Farmers Group"
   ],
   "stalls": [
    "109"
   ],
   "first": "2026-06-04",
   "last": "2026-06-04",
   "buys": 1,
   "epos": "Wild Rocket Loose"
  },
  {
   "n": "Zucchini",
   "sups": [
    "Latorre's"
   ],
   "stalls": [
    "63"
   ],
   "first": "2026-06-01",
   "last": "2026-06-01",
   "buys": 1,
   "epos": "Zucchini /kg"
  }
 ]
};
