/* build-catalog.cjs — generate app2/catalog.js (PUBLIC, cost-free).
   Reads ../shopProducts.js (which carries purchase COSTS) and writes a
   catalogue that contains ONLY what a customer may see:
     category, product name, RETAIL sell price, barcode.
   NO purchase cost, NO box/wholesale cost, NO margin — nothing financial
   beyond the shelf price. The v2 customer app loads THIS, never the costy
   shopProducts.js, so costs never reach the public bundle.
   Re-run whenever sell prices change:  node app2/build-catalog.cjs        */
const fs = require('fs');
const path = require('path');

const SRC = path.join(__dirname, '..', 'shopProducts.js');
const OUT = path.join(__dirname, 'catalog.js');

// shopProducts.js is a browser global (var SHOP_PRODUCTS = [...]). Eval it in
// this (non-strict) scope so the var binding becomes visible here.
const code = fs.readFileSync(SRC, 'utf8');
// Run the browser-global script in its own scope and hand back the array.
const SHOP_PRODUCTS = new Function(code + '\nreturn SHOP_PRODUCTS;')();

// Categories NOT offered for delivery/ordering (owner 2026-06-12: no cafe
// counter items, nothing "club", no croissants, no wastage lines).
const EXCLUDE_CAT = /^(cafe\b|cafe-|club\b|croissant|wastage)/i;
const EXCLUDE_NAME = /club\s*membership|croissant|wastage/i;

// Column map: [category0, stall1, phone2, name3, defaultQty4, boxPrice5,
//              cost6, sellPrice7, mustCheck8, barcode9]  — we keep 0,3,7,9 only.
const rows = (Array.isArray(SHOP_PRODUCTS) ? SHOP_PRODUCTS : [])
  .filter((r) => Array.isArray(r) && String(r[3] == null ? '' : r[3]).trim())
  .filter((r) => !EXCLUDE_CAT.test(String(r[0] == null ? '' : r[0]).trim()))
  .filter((r) => !EXCLUDE_NAME.test(String(r[3] == null ? '' : r[3])))
  .map((r) => ({
    c: String(r[0] == null ? '' : r[0]).trim(), // category
    n: String(r[3]).trim(),                      // name
    s: (r[7] == null || r[7] === '') ? null : Number(r[7]), // sell (retail)
    b: r[9] == null ? '' : String(r[9]).trim()   // barcode
  }));

const banner =
  '/* catalog.js — PUBLIC product list for the Happy Days v2 customer app.\n' +
  '   AUTO-GENERATED by app2/build-catalog.cjs — do not hand-edit.\n' +
  '   Contains ONLY: category, name, retail sell price, barcode.\n' +
  '   Deliberately carries NO purchase cost / wholesale cost / margin —\n' +
  '   no financial data of any kind reaches the customer-facing bundle. */\n';

const body =
  'window.HD_CATALOG = [\n' +
  rows.map((r) => '  ' + JSON.stringify(r)).join(',\n') +
  '\n];\n';

fs.writeFileSync(OUT, banner + body, 'utf8');
console.log('wrote ' + OUT + ' — ' + rows.length + ' products, cost-free.');
