/* =========================================================================
   store.js — Happy Days v2 data layer (Builder B)
   Catalogue, buy list, auth, Firebase REST sync, customers/orders/tiers,
   tier pricing, and the app-wide event bus. No frameworks, no SDKs.
   ========================================================================= */

const FB = {
  apiKey: 'AIzaSyBlnVVwGbNW6N3ErAZMpqNIROjGkv_D3nc',
  databaseURL: 'https://happydaysgrocer-dc980-default-rtdb.asia-southeast1.firebasedatabase.app'
};

/* ---------- version (one source of truth, shown in gate + More) ----------
   Scheme: v3.1, v3.2, … — bump the minor on each shipped milestone.
   PRICES_CHECKED = the date the catalogue was last verified against the
   live EPOS till prices (update whenever the price sync is run). */
export const VERSION = 'v3.43';
export const PRICES_CHECKED = '16 Jun 2026';

/* ---------- tiny utilities ---------- */

const round2 = (x) => Math.round(x * 100) / 100;

const num = (v) => {
  const n = parseFloat(v);
  return Number.isFinite(n) ? n : null;
};

function genId(prefix) {
  return prefix + Date.now().toString(36) + Math.random().toString(36).slice(2, 7);
}

/** Local calendar date (NOT toISOString — at the 4am market UTC is yesterday). */
function todayStr() {
  const d = new Date();
  const p = (n) => String(n).padStart(2, '0');
  return d.getFullYear() + '-' + p(d.getMonth() + 1) + '-' + p(d.getDate());
}

/* localStorage wrapper that never throws (private mode / quota). */
const LS = {
  get(key, fallback) {
    try {
      const raw = localStorage.getItem(key);
      return raw == null ? fallback : JSON.parse(raw);
    } catch (e) { return fallback; }
  },
  set(key, val) {
    try { localStorage.setItem(key, JSON.stringify(val)); } catch (e) { /* ignore */ }
  },
  del(key) {
    try { localStorage.removeItem(key); } catch (e) { /* ignore */ }
  }
};

/* ---------- event bus (singleton) ---------- */

const _listeners = {};
const BUS = {
  on(evt, fn) { (_listeners[evt] = _listeners[evt] || []).push(fn); },
  emit(evt, data) {
    (_listeners[evt] || []).forEach((fn) => {
      try { fn(data); } catch (e) { /* a bad listener must not break the app */ }
    });
  }
};
export function bus() { return BUS; }

/* =========================================================================
   CATALOGUE — loaded from ./catalog.js (non-module global HD_CATALOG),
   a PUBLIC, COST-FREE product list generated by app2/build-catalog.cjs.
   Row shape: { c: category, n: name, s: sellPrice, b: barcode }.
   There is deliberately NO cost field anywhere in the customer app —
   purchase costs / wholesale costs / margins never reach this bundle.
   ========================================================================= */

let CATALOG = [];
const CATALOG_BY_KEY = new Map();
let _catalogPromise = null;

function buildCatalog(rows) {
  CATALOG = [];
  CATALOG_BY_KEY.clear();
  (Array.isArray(rows) ? rows : []).forEach((r) => {
    if (!r || typeof r !== 'object') return;
    const cat = String(r.c == null ? '' : r.c).trim();
    const name = String(r.n == null ? '' : r.n).trim();
    if (!name) return;
    const item = {
      key: cat + '||' + name,         // this exact key joins all stores
      cat,
      group: String(r.g || cat).trim(), // Woolies-style aisle (display only)
      name,
      sell: num(r.s),                 // retail shelf price only — no cost
      barcode: r.b == null ? '' : String(r.b).trim()
    };
    CATALOG.push(item);
    CATALOG_BY_KEY.set(item.key, item);
  });
}

/* Inject <script src="catalog.js"> (it is NOT a module) and wait for
   window.HD_CATALOG. Caches the rows in localStorage so the catalogue
   still works on an offline cold start. */
function loadCatalog() {
  return new Promise((resolve) => {
    if (window.HD_CATALOG) return resolve(window.HD_CATALOG);
    const s = document.createElement('script');
    s.src = 'catalog.js';
    let settled = false;
    const finish = (rows) => { if (!settled) { settled = true; resolve(rows); } };
    s.onload = () => {
      // The global is set synchronously by the script, but poll briefly
      // as cheap insurance against any deferred assignment.
      let tries = 0;
      const tick = () => {
        if (window.HD_CATALOG) return finish(window.HD_CATALOG);
        if (++tries > 60) return finish(null);   // ~3s then give up
        setTimeout(tick, 50);
      };
      tick();
    };
    s.onerror = () => finish(null);              // offline / 404
    document.head.appendChild(s);
  });
}

export async function initCatalog() {
  if (CATALOG.length) return CATALOG;            // idempotent
  if (_catalogPromise) return _catalogPromise;
  _catalogPromise = (async () => {
    const rows = await loadCatalog();
    if (Array.isArray(rows) && rows.length) {
      LS.set('hd2.catalogCache2', rows);         // cost-free cache (v2 key)
      buildCatalog(rows);
    } else {
      buildCatalog(LS.get('hd2.catalogCache2', []));
    }
    LS.del('hd2.catalogCache');                  // purge old cost-bearing cache
    _applySecureCache();                          // v3: overlay any cached costs (offline)
    const _ch = LS.get('hd3.hist', null); if (_ch) _hist = _ch;   // offline history
    BUS.emit('change');
    return CATALOG;
  })();
  return _catalogPromise;
}

export function catalog() { return CATALOG; }

/* =========================================================================
   SECURE cost/sales overlay  (v3 IN-HOUSE app only, post-login)
   The static catalogue (catalog.js) carries names + SELL only. After a
   director signs in, the LOCKED /catalog node yields {SHOP_PRODUCTS, EPOS90}
   with wholesale COSTS + 90-day margins. We overlay cost onto CATALOG items
   in memory and keep the EPOS stats. NONE of this is ever written to a
   static file — costs reach the browser only over an authenticated read.
   ========================================================================= */
let _secureLoaded = false;
let _epos = {};   // lowercased name -> {qty, revIncVAT, cost, margin, marginPerc}

export function secureLoaded() { return _secureLoaded; }

function _overlayProducts(sp) {
  const costByKey = new Map();
  (Array.isArray(sp) ? sp : []).forEach((row) => {
    if (!Array.isArray(row)) return;
    const cat = String(row[0] == null ? '' : row[0]).trim();
    const name = String(row[3] == null ? '' : row[3]).trim();
    const cost = num(row[6]);
    if (name && cost != null) costByKey.set(cat + '||' + name, cost);
  });
  CATALOG.forEach((it) => { const c = costByKey.get(it.key); if (c != null) it.cost = c; });
  return costByKey.size;
}

function _applySecureCache() {
  const cached = LS.get('hd3.secure', null);
  if (!cached) return;
  if (_overlayProducts(cached.products)) _secureLoaded = true;
  _epos = {};
  (cached.epos || []).forEach((x) => { if (x && x.name) _epos[String(x.name).toLowerCase()] = x; });
}

/* Fallback cost source (v3.27). The locked /catalog vault needs an owner upload
   that is currently blocked (the Firebase password can't be recovered). The same
   wholesale COSTS already ship in the PUBLIC shopProducts.js — the exact file the
   build reads and that is already downloadable from the site — so when the vault
   is empty we overlay costs straight from it. This is a DIRECTORS-ONLY app and
   adds no exposure beyond what shopProducts.js already is. Once the vault is
   restored, loadSecureCatalog uses it first and this never runs. */
async function loadPublicCosts() {
  try {
    const r = await fetch('../shopProducts.js?cb=' + VERSION);
    if (!r.ok) return false;
    const src = await r.text();
    const sp = new Function(src + '\nreturn (typeof SHOP_PRODUCTS !== "undefined") ? SHOP_PRODUCTS : [];')();
    if (!Array.isArray(sp) || !sp.length) return false;
    const n = _overlayProducts(sp);
    if (n) {
      _secureLoaded = true;
      LS.set('hd3.secure', { products: sp, epos: [], at: Date.now() });
      BUS.emit('change');
    }
    return !!n;
  } catch (e) { return false; }
}

/** Pull {SHOP_PRODUCTS, EPOS90} from the locked /catalog node and overlay; if
    that vault is empty/unreachable, fall back to the public cost file. */
export async function loadSecureCatalog() {
  let t = null;
  try { t = await auth.token(); } catch (e) { t = null; }
  if (t) {
    try {
      const r = await fetch(FB.databaseURL + '/catalog.json?auth=' + encodeURIComponent(t));
      if (r.ok) {
        const blob = await r.json();
        if (blob && blob.json) {                      // node populated
          const data = JSON.parse(blob.json);
          const n = _overlayProducts(data.SHOP_PRODUCTS);
          const items = (data.EPOS90 && Array.isArray(data.EPOS90.items)) ? data.EPOS90.items : [];
          _epos = {};
          items.forEach((x) => { if (x && x.name) _epos[String(x.name).toLowerCase()] = x; });
          _secureLoaded = !!(n || items.length);
          LS.set('hd3.secure', { products: data.SHOP_PRODUCTS || [], epos: items, at: Date.now() });
          BUS.emit('change');
          if (_secureLoaded) return true;
        }
      }
    } catch (e) { /* fall through to the public-cost fallback */ }
  }
  return await loadPublicCosts();                      // vault empty/blocked
}

/* ===========================================================================
   HISTORY (operational): purchase catalogue, 90-day sales, wastage. Loaded from
   the v1 root files that the build scripts keep current. The SENSITIVE finance
   ledger (bank, supplier-invoice $ totals, capital, contributions) is
   DELIBERATELY excluded — by owner instruction it stays only on the PC, never
   on the app or web.
   =========================================================================== */
let _hist = { store: null, sales: null, waste: null };
export function histData() { return _hist; }

async function _fetchGlobal(path, globalName) {
  try {
    const r = await fetch(path + '?cb=' + VERSION);
    if (!r.ok) return null;
    const src = await r.text();
    return new Function(src + '\nreturn (typeof ' + globalName + ' !== "undefined") ? ' + globalName + ' : null;')();
  } catch (e) { return null; }
}

export async function loadHistory() {
  const [store, sales, waste] = await Promise.all([
    _fetchGlobal('../storeCatalog.js', 'STORE_CATALOG'),
    _fetchGlobal('../epos90.js', 'EPOS90'),
    _fetchGlobal('../wastage.js', 'FV_WASTAGE')
  ]);
  let any = false;
  if (store) { _hist.store = store; any = true; }
  if (sales) { _hist.sales = sales; any = true; }
  if (waste) { _hist.waste = waste; any = true; }
  if (any) { LS.set('hd3.hist', _hist); BUS.emit('change'); }
  return _hist;
}

export function costOf(key) {
  const it = CATALOG_BY_KEY.get(key);
  return it && typeof it.cost === 'number' ? it.cost : null;
}

export function marginInfo(key) {
  const it = CATALOG_BY_KEY.get(key);
  if (!it) return null;
  const cost = (typeof it.cost === 'number') ? it.cost : null;
  const sell = (typeof it.sell === 'number') ? it.sell : null;
  let profit = null, marginPct = null;
  if (cost != null && sell != null && sell > 0) {
    profit = round2(sell - cost);
    marginPct = Math.round((profit / sell) * 100);
  }
  return { cost, sell, profit, marginPct };
}

export function eposFor(name) { return _epos[String(name || '').toLowerCase()] || null; }

export function categories() {
  const seen = new Set();
  CATALOG.forEach((i) => { if (i.cat) seen.add(i.cat); });
  return Array.from(seen).sort((a, b) => a.localeCompare(b));
}

/* Woolies-style aisle order: produce first (kept exactly as-is), then the
   grocery aisles. Unknown groups append alphabetically at the end. */
const GROUP_ORDER = [
  'A-B', 'C-G', 'H-O', 'P-R', 'S-Z', 'Herbs',
  'Dairy & Fridge', 'Pantry', 'Snacks & Confectionery',
  'Drinks', 'Freezer', 'Household & Personal Care'
];

function groupRank(g) {
  const i = GROUP_ORDER.indexOf(g);
  return i < 0 ? 999 : i;
}

/** Distinct aisles, in shopping order (produce first, then grocery). */
export function groups() {
  const seen = new Set();
  CATALOG.forEach((i) => { if (i.group) seen.add(i.group); });
  return Array.from(seen).sort((a, b) =>
    groupRank(a) - groupRank(b) || a.localeCompare(b));
}

/** Distinct categories (sections), aisle-ordered; optionally within one aisle. */
export function orderedCats(group) {
  const seen = new Map();   // cat -> group
  CATALOG.forEach((i) => {
    if (!i.cat) return;
    if (group && i.group !== group) return;
    if (!seen.has(i.cat)) seen.set(i.cat, i.group);
  });
  return Array.from(seen.keys()).sort((a, b) =>
    groupRank(seen.get(a)) - groupRank(seen.get(b)) || a.localeCompare(b));
}

/** Multi-word, any-order match on the product name. "" -> full catalogue. */
export function searchCatalog(q) {
  const terms = String(q == null ? '' : q).toLowerCase().split(/\s+/).filter(Boolean);
  if (!terms.length) return CATALOG.slice();
  return CATALOG.filter((i) => {
    const name = i.name.toLowerCase();
    return terms.every((t) => name.includes(t));
  });
}

/* =========================================================================
   BUY LIST — market shopping list, persisted as 'hd2.buylist' {key: qty}
   ========================================================================= */

let _buyMap = LS.get('hd2.buylist', {});
if (typeof _buyMap !== 'object' || _buyMap === null || Array.isArray(_buyMap)) _buyMap = {};

function persistBuy() {
  LS.set('hd2.buylist', _buyMap);
  BUS.emit('change');
}

export const buy = {
  qty(key) { return _buyMap[key] || 0; },
  set(key, qty) {
    qty = Number(qty);
    if (!Number.isFinite(qty) || qty <= 0) delete _buyMap[key];
    else _buyMap[key] = qty;
    persistBuy();
  },
  add(key, delta) {
    buy.set(key, (_buyMap[key] || 0) + (Number(delta) || 0));
  },
  entries() { return Object.entries(_buyMap); },         // [[key, qty], ...]
  count() { return Object.keys(_buyMap).length; },        // distinct items
  clear() { _buyMap = {}; persistBuy(); }
};

/* =========================================================================
   AUTH — same Firebase accounts as the old app.
   email = username + '@happydaysgrocer.app'. Login-only (no auto-signUp).
   Blob {idToken, refreshToken, expiresAt, uid, email} in 'hd2.auth'.
   ========================================================================= */

let _auth = LS.get('hd2.auth', null);

function setAuth(blob) {
  _auth = blob;
  if (blob) LS.set('hd2.auth', blob); else LS.del('hd2.auth');
  BUS.emit('change');
}

function friendlyAuthError(code) {
  code = String(code || '');
  if (code.indexOf('EMAIL_NOT_FOUND') === 0 ||
      code.indexOf('INVALID_PASSWORD') === 0 ||
      code.indexOf('INVALID_LOGIN_CREDENTIALS') === 0) return 'Wrong username or password.';
  if (code.indexOf('TOO_MANY_ATTEMPTS') === 0) return 'Too many attempts — wait a minute and try again.';
  if (code.indexOf('USER_DISABLED') === 0) return 'This account has been disabled.';
  return 'Could not sign in. Check your connection and try again.';
}

export const auth = {
  async login(username, password) {
    const u = String(username || '').trim();
    const email = u.indexOf('@') >= 0 ? u : u + '@happydaysgrocer.app';
    const res = await fetch(
      'https://identitytoolkit.googleapis.com/v1/accounts:signInWithPassword?key=' + FB.apiKey,
      {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ email, password, returnSecureToken: true })
      }
    );
    let data = {};
    try { data = await res.json(); } catch (e) { /* fall through */ }
    if (!res.ok) {
      throw new Error(friendlyAuthError(data && data.error && data.error.message));
    }
    const blob = {
      idToken: data.idToken,
      refreshToken: data.refreshToken,
      // refresh 60s early so an in-flight request never carries a dead token
      expiresAt: Date.now() + (Number(data.expiresIn) || 3600) * 1000 - 60000,
      uid: data.localId,
      email
    };
    // Customer login? /custUsers/<uid> maps a Firebase uid to its customer
    // record (written by staff when they create the login). Best effort —
    // until the security rules are published this just comes back denied.
    try {
      const r = await fetch(FB.databaseURL + '/custUsers/' +
        encodeURIComponent(data.localId) + '.json?auth=' + encodeURIComponent(data.idToken));
      if (r.ok) {
        const cid = await r.json();
        if (typeof cid === 'string' && cid) blob.custId = cid;
      }
    } catch (e) { /* offline / rules not live yet */ }
    setAuth(blob);
    return auth.user();
  },

  logout() { setAuth(null); },

  /** Set a new password for the signed-in account (the phone's live session
      authorises it — no old password needed). Returns the fresh tokens into
      the auth blob so the session continues uninterrupted. */
  async changePassword(newPassword) {
    const t = await auth.token();
    if (!t) throw new Error('Sign in first.');
    const res = await fetch(
      'https://identitytoolkit.googleapis.com/v1/accounts:update?key=' + FB.apiKey,
      {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ idToken: t, password: newPassword, returnSecureToken: true })
      }
    );
    let data = {};
    try { data = await res.json(); } catch (e) { /* fall through */ }
    if (!res.ok) {
      const code = String((data && data.error && data.error.message) || '');
      if (code.indexOf('CREDENTIAL_TOO_OLD') === 0 || code.indexOf('TOKEN_EXPIRED') === 0) {
        throw new Error('For safety, sign out and sign back in, then change the password.');
      }
      if (code.indexOf('WEAK_PASSWORD') === 0) throw new Error('Password too short — use 6+ characters.');
      throw new Error('Could not change the password. Check your connection and try again.');
    }
    setAuth({
      idToken: data.idToken || t,
      refreshToken: data.refreshToken || _auth.refreshToken,
      expiresAt: Date.now() + (Number(data.expiresIn) || 3600) * 1000 - 60000,
      uid: data.localId || _auth.uid,
      email: _auth.email,
      custId: _auth.custId || undefined
    });
    return true;
  },

  user() {
    if (!_auth) return null;
    return {
      uid: _auth.uid, email: _auth.email,
      name: String(_auth.email || '').split('@')[0],
      custId: _auth.custId || null
    };
  },

  /** Resolves a valid idToken (auto-refresh) or null when signed out. */
  async token() {
    if (!_auth) return null;
    if (Date.now() < _auth.expiresAt) return _auth.idToken;
    try {
      const res = await fetch('https://securetoken.googleapis.com/v1/token?key=' + FB.apiKey, {
        method: 'POST',
        headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
        body: 'grant_type=refresh_token&refresh_token=' + encodeURIComponent(_auth.refreshToken)
      });
      if (!res.ok) {
        // 400/401/403 => refresh token revoked/invalid: sign out cleanly.
        if (res.status === 400 || res.status === 401 || res.status === 403) {
          setAuth(null);
          return null;
        }
        return _auth.idToken; // transient server error: try the stale token
      }
      const d = await res.json();
      setAuth({
        idToken: d.id_token,
        refreshToken: d.refresh_token || _auth.refreshToken,
        expiresAt: Date.now() + (Number(d.expires_in) || 3600) * 1000 - 60000,
        uid: d.user_id || _auth.uid,
        email: _auth.email,
        custId: _auth.custId || undefined   // keep the customer binding
      });
      return _auth.idToken;
    } catch (e) {
      return _auth.idToken; // offline: stale token; callers tolerate failure
    }
  }
};

/** The customer id bound to the signed-in login, or null for staff/guests. */
export function customerId() {
  return (_auth && _auth.custId) || null;
}

/* Fire-and-forget PATCH to an arbitrary RTDB path (no local mirror). */
function fbPatch(path, body) {
  if (!_auth) return Promise.resolve();
  return auth.token().then((t) => {
    if (!t) return;
    return fetch(FB.databaseURL + '/' + path + '.json?auth=' + encodeURIComponent(t), {
      method: 'PATCH',
      body: JSON.stringify(body)
    });
  }).catch(() => { /* offline / rules pending */ });
}

/**
 * STAFF action: create a Firebase login for a customer and bind it via
 * /custUsers/<uid> = custId. Never touches the staff member's own session
 * (the sign-up response tokens are deliberately ignored).
 */
export async function createCustomerLogin(custId, username, password) {
  const u = String(username || '').trim();
  const email = u.indexOf('@') >= 0 ? u : u + '@happydaysgrocer.app';
  const res = await fetch(
    'https://identitytoolkit.googleapis.com/v1/accounts:signUp?key=' + FB.apiKey,
    {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ email, password, returnSecureToken: true })
    }
  );
  let d = {};
  try { d = await res.json(); } catch (e) { /* fall through */ }
  if (!res.ok) {
    const code = String(d && d.error && d.error.message || '');
    if (code.indexOf('EMAIL_EXISTS') === 0) throw new Error('That username is already taken');
    if (code.indexOf('WEAK_PASSWORD') === 0) throw new Error('Password too weak — 6+ characters');
    throw new Error('Could not create the login');
  }
  await fbPatch('custUsers', { [d.localId]: custId });
  return { uid: d.localId, email };
}

/* =========================================================================
   FIREBASE MIRRORS — customers / orders(custorders) / tiers(pricetiers)
   Offline-first: render from the local mirror instantly, pull() refreshes.
   ========================================================================= */

/* local concept name -> remote node name */
const REMOTE = { customers: 'customers', orders: 'custorders', tiers: 'pricetiers', runs: 'runs', specials: 'specials', standing: 'standingorders', avail: 'availability', buyrun: 'buyrun', stock: 'stock', barcodes: 'barcodes', boxsizes: 'boxsizes', tillqueue: 'tillqueue', stalls: 'stalls' };
const LSKEY = { customers: 'hd2.customers', orders: 'hd2.orders', tiers: 'hd2.tiers', runs: 'hd2.runs', specials: 'hd2.specials', standing: 'hd2.standing', avail: 'hd2.avail', buyrun: 'hd3.buyrun', stock: 'hd3.stock', barcodes: 'hd3.barcodes', boxsizes: 'hd3.boxsizes', tillqueue: 'hd3.tillqueue', stalls: 'hd3.stalls' };

function localNameFor(node) {
  if (node === 'custorders' || node === 'orders') return 'orders';
  if (node === 'pricetiers' || node === 'tiers') return 'tiers';
  return node;
}

const mirror = {
  customers: LS.get(LSKEY.customers, {}) || {},
  orders: LS.get(LSKEY.orders, {}) || {},
  tiers: LS.get(LSKEY.tiers, {}) || {},
  runs: LS.get(LSKEY.runs, {}) || {},
  specials: LS.get(LSKEY.specials, {}) || {},
  standing: LS.get(LSKEY.standing, {}) || {},
  avail: LS.get(LSKEY.avail, {}) || {},
  buyrun: LS.get(LSKEY.buyrun, {}) || {},
  stock: LS.get(LSKEY.stock, {}) || {},
  barcodes: LS.get(LSKEY.barcodes, {}) || {},
  boxsizes: LS.get(LSKEY.boxsizes, {}) || {},
  tillqueue: LS.get(LSKEY.tillqueue, {}) || {},
  stalls: LS.get(LSKEY.stalls, {}) || {}
};

// Seeds are deliberately ALL shelf-price: the real per-group rules live in
// the LOCKED /pricetiers node (set via More -> Price levels) and sync after
// login. Never bake margin/markup percentages into this public file.
const DEFAULT_TIERS = {
  retail:     { id: 'retail',     name: 'Retail',     rule: { type: 'shop' } },
  cafe:       { id: 'cafe',       name: 'Cafe',       rule: { type: 'shop' } },
  restaurant: { id: 'restaurant', name: 'Restaurant', rule: { type: 'shop' } },
  agedcare:   { id: 'agedcare',   name: 'Aged Care',  rule: { type: 'shop' } },
  wholesale:  { id: 'wholesale',  name: 'Wholesale',  rule: { type: 'shop' } }
};
const TIER_ORDER = ['retail', 'cafe', 'restaurant', 'agedcare', 'wholesale'];

function seedTiersIfEmpty() {
  if (Object.keys(mirror.tiers).length === 0) {
    mirror.tiers = JSON.parse(JSON.stringify(DEFAULT_TIERS));
    LS.set(LSKEY.tiers, mirror.tiers);
  }
}
seedTiersIfEmpty(); // pricing must work before the first sync ever happens

/* ---------- delivery runs (cut-off + delivery days) ---------- */

const DEFAULT_RUNS = {
  morning: {
    id: 'morning', name: 'Morning delivery', code: 'AM',
    cutoffTime: '21:00', cutoffDayOffset: -1,   // order by 9pm the night before
    deliveryDays: [1, 2, 3, 4, 5, 6],           // Mon–Sat (0 = Sun)
    active: true
  }
};

function seedRunsIfEmpty() {
  if (Object.keys(mirror.runs).length === 0) {
    mirror.runs = JSON.parse(JSON.stringify(DEFAULT_RUNS));
    LS.set(LSKEY.runs, mirror.runs);
  }
}
seedRunsIfEmpty();

/**
 * Fire-and-forget PATCH. Also keeps the local mirror + localStorage in sync
 * (offline-first: the write is visible immediately, the network is best
 * effort). No-op on the network when logged out. Accepts either the local
 * name ('orders') or the remote node name ('custorders').
 */
export function patch(node, id, rec) {
  const local = localNameFor(node);
  const remote = REMOTE[local] || node;
  if (mirror[local] && id != null) {
    mirror[local][id] = rec;
    LS.set(LSKEY[local], mirror[local]);
  }
  if (!_auth) return; // logged out -> local only
  auth.token().then((t) => {
    if (!t) return;
    // No Content-Type header: RTDB accepts the raw body and a "simple"
    // request avoids a CORS preflight round trip on every keystroke-save.
    return fetch(FB.databaseURL + '/' + remote + '.json?auth=' + encodeURIComponent(t), {
      method: 'PATCH',
      body: JSON.stringify({ [id]: rec })
    });
  }).catch(() => queueWrite(remote, id, rec));
}

/* ---------- offline outbox (v3.3, DESIGN.md) ----------
   A write made with no market signal lands in the mirror instantly (above)
   and queues here for the network; the queue flushes on reconnect, on every
   pull(), and via Sync now. Only NETWORK failures queue — a 4xx (auth/
   permission) response resolves the fetch and is deliberately NOT retried,
   it would never succeed and must not loop. Per node+id the LAST write wins
   so a queue can't replay a stale quantity over a newer one. */

let outbox = LS.get('hd3.outbox', []) || [];

function queueWrite(node, id, rec) {
  if (id == null) return;
  outbox = outbox.filter((w) => !(w.node === node && w.id === id)); // last wins
  outbox.push({ node, id, rec });
  LS.set('hd3.outbox', outbox);
  BUS.emit('outbox');
}

export function outboxCount() { return outbox.length; }

let _flushing = false;
export async function flushOutbox() {
  if (_flushing || !outbox.length || !_auth) return;
  _flushing = true;
  try {
    const t = await auth.token();
    if (!t) return;
    while (outbox.length) {
      const w = outbox[0];
      try {
        await fetch(FB.databaseURL + '/' + w.node + '.json?auth=' + encodeURIComponent(t), {
          method: 'PATCH',
          body: JSON.stringify({ [w.id]: w.rec })
        });
      } catch (e) { return; }          // still offline — keep the rest, retry later
      outbox.shift();
      LS.set('hd3.outbox', outbox);
      BUS.emit('outbox');
    }
  } catch (e) {
    /* token refresh failed — retry on the next trigger */
  } finally {
    _flushing = false;
  }
}

if (typeof window !== 'undefined') {
  window.addEventListener('online', () => { flushOutbox(); });
}

/* ---------- stocktake + progressive barcodes (v3.4, DESIGN.md) ----------
   /stock = latest on-hand count per product (id-keyed records — product
   keys contain '/'). /barcodes = the team's own barcode→product bindings,
   layered OVER the static catalogue's barcode field so a wrong or missing
   static code is correctable from the shop floor, no rebuild needed. */

/** Latest count record for a product key, or null. */
export function stockFor(key) {
  let best = null;
  for (const r of Object.values(mirror.stock)) {
    if (r && r.key === key && (!best || String(r.at || '') >= String(best.at || ''))) best = r;
  }
  return best;
}

/** Commit one counted quantity. */
export function setStockCount(key, name, qty) {
  let rec = Object.values(mirror.stock).find((r) => r && r.key === key);
  if (!rec) rec = { id: genId('st'), key, name: name || key };
  rec.qty = Number(qty) || 0;
  rec.at = todayStr();
  rec.by = (_auth && _auth.email) ? String(_auth.email).split('@')[0] : '';
  patch('stock', rec.id, rec);
  BUS.emit('change');
}

/** Resolve a scanned barcode to a product key: the team's assignments win
    (they correct the static data), then the static catalogue's own field. */
export function keyForBarcode(code) {
  code = String(code || '').trim();
  if (!code) return null;
  for (const r of Object.values(mirror.barcodes)) {
    if (r && r.code === code && r.key) return r.key;
  }
  const hit = CATALOG.find((p) => p.barcode && String(p.barcode) === code);
  return hit ? hit.key : null;
}

/** Owner-set box-size overrides from /boxsizes (written by the classic app's
    "set box size", shared team-wide). Map: lowercased name -> {per, by}. */
export function boxOverrides() {
  const out = {};
  for (const r of Object.values(mirror.boxsizes)) {
    if (r && r.name && +r.per > 0) {
      out[String(r.name).toLowerCase().trim()] = { per: +r.per, by: r.by };
    }
  }
  return out;
}

/** Bind a barcode to a product (one record per code; re-assign overwrites). */
export function assignBarcode(code, key, name) {
  code = String(code || '').trim();
  if (!code || !key) return;
  let rec = Object.values(mirror.barcodes).find((r) => r && r.code === code);
  if (!rec) rec = { id: genId('bc'), code };
  rec.key = key;
  rec.name = name || key;
  patch('barcodes', rec.id, rec);
  BUS.emit('change');
}

/**
 * Pull the 3 nodes into the local mirrors. NEVER rejects — on any network
 * or auth failure it resolves with the stale mirrors. Remote records win
 * per-id, but ids that only exist locally (created offline) are kept.
 */
export async function pull() {
  seedTiersIfEmpty();
  seedRunsIfEmpty();
  let t = null;
  try { t = await auth.token(); } catch (e) { /* treat as logged out */ }
  if (!t) {
    try { generateStandingOrders(); } catch (e) { /* local-only generation */ }
    BUS.emit('change');
    return;
  }
  if (customerId()) return pullCustomer(t);   // scoped: own record + own orders

  const getNode = async (node) => {
    const res = await fetch(FB.databaseURL + '/' + node + '.json?auth=' + encodeURIComponent(t));
    if (!res.ok) throw new Error(node + ' HTTP ' + res.status);
    return res.json();
  };

  try {
    const [cust, ord, tr, rn, sp, st, av, br, stk, bc, bx, tq, stl] = await Promise.all([
      getNode(REMOTE.customers), getNode(REMOTE.orders), getNode(REMOTE.tiers), getNode(REMOTE.runs), getNode(REMOTE.specials), getNode(REMOTE.standing), getNode(REMOTE.avail), getNode(REMOTE.buyrun),
      // newer nodes — never let them break the core sync
      getNode(REMOTE.stock).catch(() => null), getNode(REMOTE.barcodes).catch(() => null),
      getNode(REMOTE.boxsizes).catch(() => null), getNode(REMOTE.tillqueue).catch(() => null),
      getNode(REMOTE.stalls).catch(() => null)
    ]);
    if (sp && typeof sp === 'object') mirror.specials = Object.assign({}, mirror.specials, sp);
    if (st && typeof st === 'object') mirror.standing = Object.assign({}, mirror.standing, st);
    if (av && typeof av === 'object') mirror.avail = Object.assign({}, mirror.avail, av);
    if (br && typeof br === 'object') mirror.buyrun = Object.assign({}, mirror.buyrun, br);
    if (stk && typeof stk === 'object') mirror.stock = Object.assign({}, mirror.stock, stk);
    if (bc && typeof bc === 'object') mirror.barcodes = Object.assign({}, mirror.barcodes, bc);
    if (bx && typeof bx === 'object') mirror.boxsizes = Object.assign({}, mirror.boxsizes, bx);
    if (tq && typeof tq === 'object') mirror.tillqueue = Object.assign({}, mirror.tillqueue, tq);
    if (stl && typeof stl === 'object') mirror.stalls = Object.assign({}, mirror.stalls, stl);
    if (cust && typeof cust === 'object') mirror.customers = Object.assign({}, mirror.customers, cust);
    if (ord && typeof ord === 'object') mirror.orders = Object.assign({}, mirror.orders, ord);
    if (tr && typeof tr === 'object' && Object.keys(tr).length) {
      mirror.tiers = Object.assign({}, mirror.tiers, tr);
    } else {
      // Remote tier node is empty: seed it with the defaults (fire & forget).
      fetch(FB.databaseURL + '/' + REMOTE.tiers + '.json?auth=' + encodeURIComponent(t), {
        method: 'PATCH',
        body: JSON.stringify(DEFAULT_TIERS)
      }).catch(() => {});
    }
    if (rn && typeof rn === 'object' && Object.keys(rn).length) {
      mirror.runs = Object.assign({}, mirror.runs, rn);
    } else {
      // Remote runs node is empty: seed it with the defaults (fire & forget).
      fetch(FB.databaseURL + '/' + REMOTE.runs + '.json?auth=' + encodeURIComponent(t), {
        method: 'PATCH',
        body: JSON.stringify(DEFAULT_RUNS)
      }).catch(() => {});
    }
    LS.set(LSKEY.customers, mirror.customers);
    LS.set(LSKEY.orders, mirror.orders);
    LS.set(LSKEY.tiers, mirror.tiers);
    LS.set(LSKEY.runs, mirror.runs);
    LS.set(LSKEY.specials, mirror.specials);
    LS.set(LSKEY.standing, mirror.standing);
    LS.set(LSKEY.avail, mirror.avail);
    LS.set(LSKEY.buyrun, mirror.buyrun);
    LS.set(LSKEY.stock, mirror.stock);
    LS.set(LSKEY.barcodes, mirror.barcodes);
    LS.set(LSKEY.boxsizes, mirror.boxsizes);
    LS.set(LSKEY.tillqueue, mirror.tillqueue);
    LS.set(LSKEY.stalls, mirror.stalls);
  } catch (e) {
    /* offline or server error — keep stale mirrors, still resolve */
  }
  try { generateStandingOrders(); } catch (e) { /* never break a pull */ }
  loadSecureCatalog();   // v3: overlay costs/sales from the locked /catalog node
  loadHistory();         // v3: purchase / sales / wastage history (operational only)
  flushOutbox();         // v3.3: every pull is also a chance to drain queued writes
  BUS.emit('change');
}

/**
 * Customer-scoped pull: a customer login reads ONLY its own customer
 * record, its own orders (via the /ordersByCustomer fan-out index), and
 * the shared pricing/run/special config the rules allow it to see.
 * Never rejects; failed reads (rules pending / offline) keep stale mirrors.
 */
async function pullCustomer(t) {
  const cid = customerId();
  const get = async (p) => {
    try {
      const r = await fetch(FB.databaseURL + '/' + p + '.json?auth=' + encodeURIComponent(t));
      return r.ok ? r.json() : null;
    } catch (e) { return null; }
  };
  const [me, idx, tr, rn, sp, av] = await Promise.all([
    get('customers/' + cid), get('ordersByCustomer/' + cid),
    get('pricetiers'), get('runs'), get('specials'), get('availability')
  ]);
  if (me && typeof me === 'object') mirror.customers[cid] = me;
  if (tr && typeof tr === 'object' && Object.keys(tr).length) mirror.tiers = Object.assign({}, mirror.tiers, tr);
  if (rn && typeof rn === 'object' && Object.keys(rn).length) mirror.runs = Object.assign({}, mirror.runs, rn);
  if (sp && typeof sp === 'object') mirror.specials = Object.assign({}, mirror.specials, sp);
  if (av && typeof av === 'object') mirror.avail = Object.assign({}, mirror.avail, av);
  const ids = idx && typeof idx === 'object' ? Object.keys(idx).sort().slice(-60) : [];
  const got = await Promise.all(ids.map((id) => get('custorders/' + encodeURIComponent(id))));
  got.forEach((o) => { if (o && o.id) mirror.orders[o.id] = o; });
  LS.set(LSKEY.customers, mirror.customers);
  LS.set(LSKEY.orders, mirror.orders);
  LS.set(LSKEY.tiers, mirror.tiers);
  LS.set(LSKEY.runs, mirror.runs);
  LS.set(LSKEY.specials, mirror.specials);
  LS.set(LSKEY.avail, mirror.avail);
  BUS.emit('change');
}

/* ---------- availability — "out of stock today" ----------
   Records keyed by id (product keys contain '/' so they can't be RTDB
   child keys): { id, key, name, out:'YYYY-MM-DD' }. An item is out only
   for the stamped date, so everything auto-resets at midnight. */

export function isOut(key) {
  const today = todayStr();
  for (const a of Object.values(mirror.avail)) {
    if (a && a.key === key && a.out === today) return true;
  }
  return false;
}

export function outList() {
  const today = todayStr();
  return Object.values(mirror.avail).filter((a) => a && a.out === today);
}

export function setOut(key, name, on) {
  let rec = Object.values(mirror.avail).find((a) => a && a.key === key);
  if (!rec) {
    if (!on) return;
    rec = { id: genId('av'), key, name: name || key };
  }
  rec.out = on ? todayStr() : '';
  patch('avail', rec.id, rec);
  BUS.emit('change');
}

/* ---------- BUY RUN — always-live shared market buy list ----------
   The team's "to buy" total per product = what every OPEN customer order
   needs (rolled up live) PLUS manual additions. Manual adds are shared via
   /buyrun (id-keyed records, merge-safe) so the list is the same on every
   phone and is current the moment anyone opens it — it is never "started"
   or "reset". */

export function setBuyManual(key, name, qty) {
  let rec = Object.values(mirror.buyrun).find((b) => b && b.key === key);
  qty = Number(qty) || 0;
  if (!rec) {
    if (qty <= 0) return;
    rec = { id: genId('br'), key, name: name || key };
  }
  rec.qty = qty < 0 ? 0 : qty;
  patch('buyrun', rec.id, rec);
  BUS.emit('change');
}

export function buyManualQty(key) {
  const rec = Object.values(mirror.buyrun).find((b) => b && b.key === key);
  return rec ? (Number(rec.qty) || 0) : 0;
}

/* ---- per-product STALL overrides (owner-set, synced via /stalls) ----------
   The buy run resolves each item's stall from this override first, then falls
   back to the name-matched directory. Lets the owner pin "Stall not set" items
   and fix any wrong guess; shared to every phone. Record: {id, key, stall,
   supplier, phone}. */
export function stallOverride(key) {
  const r = Object.values(mirror.stalls).find((s) => s && s.key === key);
  return (r && (r.stall || r.supplier)) ? r : null;
}
export function setStallOverride(key, name, info) {
  info = info || {};
  let rec = Object.values(mirror.stalls).find((s) => s && s.key === key);
  if (!rec) rec = { id: genId('stl'), key };
  rec.name = name || rec.name || key;
  rec.stall = String(info.stall == null ? (rec.stall || '') : info.stall).trim();
  rec.supplier = (info.supplier == null ? (rec.supplier || '') : info.supplier).trim();
  rec.phone = (info.phone == null ? (rec.phone || '') : info.phone).trim();
  patch('stalls', rec.id, rec);
  BUS.emit('change');
  return rec;
}

/** The live buy list: orders-needed + manual, per product, with a per-customer
   breakdown. DEMAND = every OPEN order PLUS every upcoming delivery that has
   not yet passed — which is how standing (recurring restaurant/café) orders
   feed the run: they are auto-placed as 'completed' for a future deliveryDate,
   so we count them by date, not by status. Manual team adds stay SEPARATE
   (fromOrders vs manual are never merged into one anonymous number). */
export function buyRunList() {
  const today = todayStr();
  const custById = (id) => id ? (mirror.customers[id] ||
    Object.values(mirror.customers).find((c) => c && c.id === id) || null) : null;

  const need = new Map();   // key -> {key, name, cat, fromOrders, manual, parts[]}
  const add = (key, name, cat, fromOrders, manual, part) => {
    const cur = need.get(key) ||
      { key, name, cat: cat || '', fromOrders: 0, manual: 0, parts: [] };
    cur.fromOrders += fromOrders; cur.manual += manual;
    if (name && !cur.name) cur.name = name;
    if (cat && !cur.cat) cur.cat = cat;
    if (part && part.qty > 0) {
      const ex = cur.parts.find((p) => p.custId === part.custId);
      if (ex) ex.qty += part.qty; else cur.parts.push(Object.assign({}, part));
    }
    need.set(key, cur);
  };

  // demand: open orders + upcoming (not-yet-past) deliveries, incl. standing
  for (const o of Object.values(mirror.orders)) {
    if (!o || !Array.isArray(o.lines)) continue;
    const upcoming = o.status === 'open' ||
      (o.deliveryDate && o.deliveryDate >= today && o.status !== 'cancelled');
    if (!upcoming) continue;
    const cust = custById(o.custId);
    const custName = (cust && cust.name) || '';
    const tier = (cust && cust.tierId) || '';
    const forRest = tier === 'restaurant' || tier === 'cafe';
    for (const l of o.lines) {
      if (!l || !l.key) continue;
      const it = CATALOG_BY_KEY.get(l.key);
      const qty = Number(l.qty) || 0;
      add(l.key, l.name || (it && it.name), (it && it.cat) || l.sup || '', qty, 0,
        { custId: o.custId, name: custName, tier, forRest, qty, channel: o.channel || '' });
    }
  }

  // manual additions (kept separate from order demand)
  for (const b of Object.values(mirror.buyrun)) {
    if (!b || !b.key || !(Number(b.qty) > 0)) continue;
    const it = CATALOG_BY_KEY.get(b.key);
    add(b.key, b.name || (it && it.name), it && it.cat, 0, Number(b.qty) || 0, null);
  }

  return Array.from(need.values())
    .map((x) => ({
      ...x,
      total: x.fromOrders + x.manual,
      forRestaurant: x.parts.some((p) => p.forRest),
      parts: x.parts.sort((a, b) => b.qty - a.qty)
    }))
    .filter((x) => x.total > 0);
}

/* ---------- read accessors (arrays, ready to render) ---------- */

export function customers() {
  return Object.values(mirror.customers).filter(Boolean)
    .sort((a, b) => String(a.name || '').localeCompare(String(b.name || '')));
}

export function orders() {
  return Object.values(mirror.orders).filter(Boolean)
    .sort((a, b) => String(b.date || '').localeCompare(String(a.date || '')));
}

export function tiers() {
  return Object.values(mirror.tiers).filter(Boolean).sort((a, b) => {
    const ai = TIER_ORDER.indexOf(a.id), bi = TIER_ORDER.indexOf(b.id);
    return (ai < 0 ? 99 : ai) - (bi < 0 ? 99 : bi) ||
      String(a.name || '').localeCompare(String(b.name || ''));
  });
}

export function runs() {
  return Object.values(mirror.runs).filter(Boolean)
    .sort((a, b) => String(a.name || '').localeCompare(String(b.name || '')));
}

export function runById(id) {
  return (id && mirror.runs[id]) ||
    Object.values(mirror.runs).find((r) => r && r.id === id) || null;
}

/**
 * Next available delivery date for a run, honouring its cut-off.
 * cutoffDayOffset: 0 = cut-off on the delivery day, -1 = the day before, etc.
 * Returns { date:'YYYY-MM-DD', cutoffAt:ms, weekday:0-6 } or null.
 */
export function deliveryInfo(run, now, onlyDays) {
  if (!run) return null;
  now = now || new Date();
  const pad = (n) => String(n).padStart(2, '0');
  const ymd = (d) => d.getFullYear() + '-' + pad(d.getMonth() + 1) + '-' + pad(d.getDate());
  let days = (Array.isArray(run.deliveryDays) && run.deliveryDays.length)
    ? run.deliveryDays : [1, 2, 3, 4, 5, 6];
  if (Array.isArray(onlyDays) && onlyDays.length) days = days.filter((d) => onlyDays.includes(d));
  if (!days.length) return null;
  const parts = String(run.cutoffTime || '21:00').split(':');
  const hh = parseInt(parts[0], 10) || 0, mm = parseInt(parts[1], 10) || 0;
  const offset = Number(run.cutoffDayOffset) || 0;
  for (let i = 0; i < 14; i++) {
    const cand = new Date(now.getFullYear(), now.getMonth(), now.getDate() + i);
    if (!days.includes(cand.getDay())) continue;
    const cut = new Date(cand.getFullYear(), cand.getMonth(), cand.getDate() + offset, hh, mm, 0, 0);
    if (now.getTime() <= cut.getTime()) {
      return { date: ymd(cand), cutoffAt: cut.getTime(), weekday: cand.getDay() };
    }
  }
  return null;
}

/* ---------- writers ---------- */

export function saveCustomer(c) {
  if (!c.id) c.id = genId('c');
  if (!c.prices) c.prices = {};
  patch('customers', c.id, c);
  BUS.emit('change');
  return c;
}

export function saveRun(r) {
  if (!r.id) r.id = genId('run');
  patch('runs', r.id, r);
  BUS.emit('change');
  return r;
}

export function saveTier(t) {
  if (!t.id) t.id = genId('tier');
  patch('tiers', t.id, t);          // -> /pricetiers (the price-level groups)
  BUS.emit('change');
  return t;
}

export function specials() {
  return Object.values(mirror.specials).filter(Boolean);
}

export function saveSpecial(s) {
  if (!s.id) s.id = genId('sp');
  patch('specials', s.id, s);
  BUS.emit('change');
  return s;
}

/* ---------- standing (repeat) orders ---------- */

export function standingList() {
  return Object.values(mirror.standing).filter(Boolean);
}

export function standingFor(custId) {
  return Object.values(mirror.standing).find((s) => s && s.custId === custId) || null;
}

export function saveStanding(s) {
  if (!s.id) s.id = genId('st');
  patch('standing', s.id, s);
  BUS.emit('change');
  return s;
}

/**
 * Auto-place standing orders. For each active standing order, find the next
 * delivery date (run cut-off still open, weekday in the standing weekdays);
 * if not yet generated for that date, place a real order priced at TODAY'S
 * tier prices. Deterministic order id (standingId + date) makes generation
 * idempotent across devices — concurrent runs rewrite the same record.
 * Called on boot and after every pull(); cheap no-op when nothing is due.
 */
export function generateStandingOrders() {
  if (!CATALOG.length) return 0;                  // prices not loaded yet
  let made = 0;
  for (const s of Object.values(mirror.standing)) {
    if (!s || s.active === false) continue;
    if (!Array.isArray(s.lines) || !s.lines.length) continue;
    if (!Array.isArray(s.weekdays) || !s.weekdays.length) continue;
    const cust = mirror.customers[s.custId] ||
      Object.values(mirror.customers).find((c) => c && c.id === s.custId);
    if (!cust) continue;
    const run = (cust.runId && mirror.runs[cust.runId]) ||
      Object.values(mirror.runs).find((r) => r && r.active !== false);
    const di = deliveryInfo(run, null, s.weekdays);
    if (!di) continue;
    if (s.lastGenerated && s.lastGenerated >= di.date) continue;   // already done
    const oid = 'so' + s.id + '_' + di.date.replace(/-/g, '');
    if (!mirror.orders[oid]) {
      const lines = s.lines.map((l) => {
        const item = CATALOG_BY_KEY.get(l.key);
        const tp = tierPrice(s.custId, l.key);
        return {
          key: l.key,
          name: (item && item.name) || l.name || l.key,
          sup: (item && item.cat) || l.sup || '',
          unit: l.unit || '',
          qty: Number(l.qty) || 0,
          price: typeof tp === 'number' ? tp : '',
          src: 'tier'
        };
      }).filter((l) => l.qty > 0);
      if (!lines.length) continue;
      patch('custorders', oid, {
        id: oid,
        custId: s.custId,
        runId: cust.runId || (run && run.id) || '',
        date: todayStr(),
        status: 'completed',
        completed: todayStr(),
        placedAt: Date.now(),
        deliveryDate: di.date,
        orderNo: di.date.replace(/-/g, '') + '-R' + String(s.id).slice(-4),
        channel: 'standing',
        lines
      });
      fbPatch('ordersByCustomer/' + s.custId, { [oid]: true });
      made++;
    }
    s.lastGenerated = di.date;
    patch('standing', s.id, s);
  }
  if (made) BUS.emit('change');
  return made;
}

/** Active promo (flat price for all customers) on a product, or null. */
export function specialFor(key) {
  const today = todayStr();
  for (const s of Object.values(mirror.specials)) {
    if (!s || s.key !== key) continue;
    if (s.price == null || s.price === '') continue;   // cleared = inactive
    if (s.until && s.until < today) continue;           // expired
    return s;
  }
  return null;
}

export function saveOrder(o) {
  if (!o.id) o.id = genId('o');
  if (!Array.isArray(o.lines)) o.lines = [];
  patch('custorders', o.id, o);
  // Fan-out index so a customer login can list ONLY its own orders
  // (RTDB rules can't filter a whole-node read).
  if (o.custId) fbPatch('ordersByCustomer/' + o.custId, { [o.id]: true });
  BUS.emit('change');
  return o;
}

/** Find this customer's open order, or create one dated today. */
export function ensureOpenOrder(custId) {
  const existing = Object.values(mirror.orders).find(
    (o) => o && o.custId === custId && o.status === 'open'
  );
  if (existing) return existing;
  return saveOrder({
    id: genId('o'),
    custId,
    date: todayStr(),
    status: 'open',
    lines: []
  });
}

/* ---------- tier pricing ---------- */

/**
 * Price for one catalogue item for one customer.
 *   shop     -> sell
 *   shopAdj  -> round2(sell * (1 + pct/100))
 *   costPlus -> sell  (the customer app carries NO cost, so cost-plus tiers
 *               fall back to the shelf price; staff set per-customer prices
 *               via customer.prices[key], which are PRICES, never costs)
 *   manual   -> ''
 * Resolution order: per-customer price -> active special (flat promo) ->
 * the customer's price-level/group rule -> shelf.
 * Returns number | ''.
 */
export function tierPrice(custId, key) {
  const cust = mirror.customers[custId] ||
    Object.values(mirror.customers).find((c) => c && c.id === custId) || null;

  if (cust && cust.prices && cust.prices[key] != null && cust.prices[key] !== '') {
    const p = num(cust.prices[key]);
    if (p != null) return round2(p);
  }

  // An active special is a flat promo price for everyone (below per-customer).
  const sp = specialFor(key);
  if (sp) { const v = num(sp.price); if (v != null) return round2(v); }

  const tierId = (cust && cust.tierId) || 'retail';
  const tier = mirror.tiers[tierId] || DEFAULT_TIERS[tierId] ||
    mirror.tiers.retail || DEFAULT_TIERS.retail;
  const rule = (tier && tier.rule) || { type: 'shop' };

  const item = CATALOG_BY_KEY.get(key);
  if (!item) return '';

  const pct = Number(rule.pct) || 0;
  switch (rule.type) {
    case 'shop':
      return item.sell == null ? '' : item.sell;
    case 'shopAdj':
      return item.sell == null ? '' : round2(item.sell * (1 + pct / 100));
    case 'costPlus':
      // No cost in the customer app — fall back to the shelf price.
      return item.sell == null ? '' : item.sell;
    case 'manual':
    default:
      return '';
  }
}

/* ---------- till queue ---------- */

export function queueForTill(order, custName, eposCustId) {
  const qid = genId('tq');
  const lines = (order.lines || []).map((l) => ({
    key: l.key, name: l.name, qty: l.qty, price: l.price, unit: l.unit || ''
  }));
  const total = Math.round(
    lines.reduce((s, l) => s + (Number(l.qty) || 0) * (Number(l.price) || 0), 0) * 100
  ) / 100;
  const rec = {
    id: qid,
    orderId: order.id,
    custId: order.custId,
    custName: custName || '',
    eposCustId: eposCustId || null,
    status: 'queued',
    lines,
    total,
    ref: order.orderNo || order.id,
    queuedAt: new Date().toISOString(),
    tillTxnId: null,
    error: null,
    by: (_auth && _auth.email) ? String(_auth.email).split('@')[0] : ''
  };
  patch('tillqueue', qid, rec);
  BUS.emit('change');
  return rec;
}

export function tillQueueStatus(orderId) {
  for (const r of Object.values(mirror.tillqueue)) {
    if (r && r.orderId === orderId) return r;
  }
  return null;
}

export function tillqueue() {
  return Object.values(mirror.tillqueue).filter(Boolean)
    .sort((a, b) => String(b.queuedAt || '').localeCompare(String(a.queuedAt || '')));
}
